replicaCountBackend: 2
replicaCountFrontend: 2

backend:
  image:
    repository: zamshed/todo-backend
    tag: latest
  port: 5000
  # Resource requests/limits for better scheduling
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

frontend:
  image:
    repository: zamshed/todo-frontend
    tag: latest
  port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

postgres:
  image:
    repository: postgres
    tag: "15"
  postgresUser: todo_user
  postgresPassword: todo_pass
  postgresDB: todo
  storageSize: 5Gi
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
