apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo.fullname" . }}-frontend
spec:
  replicas: {{ .Values.replicaCountFrontend }}
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            - name: BACKEND_URL
              value: "http://{{ include "todo.fullname" . }}-backend:{{ .Values.backend.port }}"
          resources: {{ toYaml .Values.frontend.resources | nindent 10 }}
