apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo.fullname" . }}-backend
spec:
  replicas: {{ .Values.replicaCountBackend }}
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: POSTGRES_HOST
              value: {{ printf "%s" (include "todo.fullname" .) }}-postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.postgresDB }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.postgresUser }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.postgresPassword }}"
          resources: {{ toYaml .Values.backend.resources | nindent 10 }}
