apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo.fullname" . }}-frontend
spec:
  selector:
    app: todo-frontend
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}
  type: LoadBalancer
