apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Zamshed87/Axiler-DevOps-MicroService-Project'   # update repo URL
    targetRevision: HEAD
    path: kubernetes/helm-charts/todo-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
