apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Zamshed87/Axiler-DevOps-MicroService-Project'
    targetRevision: HEAD
    path: kubernetes/helm-charts/todo-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
